export const movies = [{
        id: 1,
        title: 'The Shawshank Redemption',
        image: "https://m.media-amazon.com/images/I/519NBNHX5BL._AC_SY580_.jpg",
        year: 1994,
        rating: 9.2,
        watched: true,
        genres: ['Crime', 'Drama'],
    },
    {
        id: 2,
        title: 'The Godfather',
        image: "https://m.media-amazon.com/images/M/MV5BM2MyNjYxNmUtYTAwNi00MTYxLWJmNWYtYzZlODY3ZTk3OTFlXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg",
        year: 1972,
        rating: 9.2,
        watched: true,
        genres: ['Crime', 'Drama'],
    },
    {
        id: 3,
        title: 'The Godfather: Part II',
        image: 'https://m.media-amazon.com/images/M/MV5BMWMwMGQzZTItY2JlNC00OWZiLWIyMDctNDk2ZDQ2YjRjMWQ0XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg',
        year: 1974,
        rating: 9.0,
        genres: ['Crime', 'Drama'],
        watched: false,
    },
    {
        id: 4,
        title: 'The Dark Knight',
        image: 'https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_.jpg',
        year: 2008,
        rating: 9.0,
        watched: false,
        genres: ['Action', 'Crime', 'Drama', 'Thriller'],
    }, {
        id: 7,
        title: 'Samaritan',
        image: 'https://upload.wikimedia.org/wikipedia/en/d/de/Samaritan2022Poster.jpg',
        year: 2022,
        rating: 9.0,
        watched: false,
        genres: ['Action'],
    },
]